language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  - WKHTMLTOPDF_VERSION="0.12.5"
  - PHANTOMJS_VERSION="latest"

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1" EXCLUDE="database_cleanup,auth_totp_password_security"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="database_cleanup,auth_totp_password_security"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1" INCLUDE="database_cleanup"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="database_cleanup"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1" INCLUDE="auth_totp_password_security"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="auth_totp_password_security"


virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc
  - ln -s ${TRAVIS_BUILD_DIR}/server_environment_files_sample ${TRAVIS_BUILD_DIR}/server_environment_files
script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
